# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3cc749495c3b50f3e272d64e8c01522cdc3c67b20e16a1c14a8dc34af3724cd499b9d80db24e0fb6779773375c52a9c3ce3b500e7641c5903057f3f1b0f32f21

test:
  secret_key_base: 2a3a82f9a0ea8db31c1008e54bd42b15a25596c9dc341a5676362f643f5c1365fc4661642fa6c521b10ab71f72737ce3b34818afc8260db7fc150904b910b200

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
